version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: captcha_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_DATABASE: captcha_service
      MYSQL_USER: captcha_user
      MYSQL_PASSWORD: captcha_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: 